metric: COCO
# num_classes: 80
num_classes: 2

TrainDataset:
  name: COCODataSet
  image_dir: train
  anno_path: annotations/instance_train.json
  dataset_dir: dataset/UDTIRI
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: val
  anno_path: annotations/instance_val.json
  dataset_dir: dataset/UDTIRI
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: annotations/instance_val.json # also support txt (like VOC's label_list.txt)
  dataset_dir: dataset/UDTIRI # if set, anno_path will be 'dataset_dir/anno_path'
